-- V2 migration: adds users, refresh_tokens, and audit_logs tables for the
-- authentication system (JWT + RBAC + MFA), and adds a nullable user_id FK
-- column to analyzed_logs so analyses can be attributed to a user.
--
-- New tables:
--   users          — 14 columns (UUID PK, bcrypt password, role CHECK, MFA, brute-force fields)
--   refresh_tokens —  5 columns (UUID PK, FK→users CASCADE, SHA-256 token hash, expiry)
--   audit_logs     —  9 columns (BIGSERIAL PK, FK→users SET NULL, JSONB details)
--
-- Modified tables:
--   analyzed_logs  — adds user_id UUID nullable FK to users (10 columns total after V1's 9)
--
-- Design decisions:
--   UUID PKs generated by gen_random_uuid() (PostgreSQL 13+ built-in, no extension needed)
--   mfa_secret stored as TEXT (encrypted at application layer with AES-256 before insert)
--   audit_logs is append-only by convention; no DELETE or UPDATE should occur on it
--   user_id in analyzed_logs is nullable to preserve existing rows with NULL user_id
--
-- NEVER modify this file after it has been applied to any environment.
-- Use a new V3__ migration for any schema changes.

-- ── users ──────────────────────────────────────────────────────────────────

CREATE TABLE users (
    id                      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email                   VARCHAR(255) NOT NULL UNIQUE,
    password_hash           VARCHAR(255) NOT NULL,
    display_name            VARCHAR(100) NOT NULL,
    role                    VARCHAR(20)  NOT NULL DEFAULT 'ANALYST',
    mfa_secret              TEXT,
    mfa_enabled             BOOLEAN      NOT NULL DEFAULT false,
    email_verified          BOOLEAN      NOT NULL DEFAULT false,
    verification_token      VARCHAR(255),
    verification_token_expiry TIMESTAMP,
    failed_login_attempts   INTEGER      NOT NULL DEFAULT 0,
    locked_until            TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT users_role_check CHECK (role IN ('ANALYST', 'KB_ADMIN', 'MANAGER'))
);

-- ── refresh_tokens ─────────────────────────────────────────────────────────

CREATE TABLE refresh_tokens (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user_id   ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- ── audit_logs ─────────────────────────────────────────────────────────────

CREATE TABLE audit_logs (
    id            BIGSERIAL    PRIMARY KEY,
    actor_id      UUID         REFERENCES users(id) ON DELETE SET NULL,
    actor_email   VARCHAR(255) NOT NULL,
    action        VARCHAR(50)  NOT NULL,
    resource_type VARCHAR(50)  NOT NULL,
    resource_id   VARCHAR(255),
    details       JSONB,
    ip_address    VARCHAR(45),
    created_at    TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_actor_created    ON audit_logs(actor_id, created_at);
CREATE INDEX idx_audit_logs_resource_created ON audit_logs(resource_type, created_at);

-- ── analyzed_logs: add user attribution column ─────────────────────────────

ALTER TABLE analyzed_logs
    ADD COLUMN user_id UUID REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_analyzed_logs_user_created ON analyzed_logs(user_id, created_at);
CREATE INDEX idx_analyzed_logs_created      ON analyzed_logs(created_at);
